cms:
  defaultValue:
    pageNum: 1
    pageSize: 30
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.172:3306/ms_as_db?serverTimezone=Asia/Shanghai
    username: root
    validation-query: SELECT 1
  profiles:
    active: dao
